_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e0ba21bf-a9d2-4c9b-aaf8-e93b5221118b
name: bugs-7319-new
mail: aminul.islam@getpantheon.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
